import { Injectable, NotFoundException, ForbiddenException, Inject } from '@nestjs/common';
import { ITaskRepository } from '../../domain/interfaces/task.repository.interface';
import { TaskEntity } from '../../domain/entities/task.entity';
import { CreateTaskDto, UpdateTaskDto } from '../dto';
import { TaskStatus, TaskPriority, TaskEventType, Task } from '@task-manager/types';
import { TaskEventService } from '../../infrastructure/events/task-event.service';

@Injectable()
export class TaskService {
  constructor(
    @Inject('ITaskRepository') private readonly taskRepository: ITaskRepository,
    private readonly taskEventService: TaskEventService,
  ) {}

  async create(
    userId: string,
    createTaskDto: CreateTaskDto,
    workspaceId?: string,
  ): Promise<TaskEntity> {
    const task = new TaskEntity(
      '', // Will be generated by repository
      userId,
      createTaskDto.title,
      createTaskDto.description,
      createTaskDto.status || TaskStatus.TODO,
      createTaskDto.priority || TaskPriority.MEDIUM,
      createTaskDto.dueDate ? new Date(createTaskDto.dueDate) : undefined,
      createTaskDto.tags || [],
      workspaceId,
    );

    const createdTask = await this.taskRepository.create(task);

    this.taskEventService.emitEvent(userId, TaskEventType.CREATED, {
      task: this.entityToTask(createdTask),
      workspaceId: createdTask.workspaceId,
    });

    return createdTask;
  }

  async findAll(userId: string, params?: any): Promise<TaskEntity[]> {
    return this.taskRepository.findByUserId(userId, params);
  }

  async findOne(id: string, userId: string): Promise<TaskEntity> {
    const task = await this.taskRepository.findById(id);

    if (!task) {
      throw new NotFoundException(`Task with ID ${id} not found`);
    }

    if (task.userId !== userId) {
      throw new ForbiddenException('You do not have access to this task');
    }

    return task;
  }

  async update(id: string, userId: string, updateTaskDto: UpdateTaskDto): Promise<TaskEntity> {
    const existingTask = await this.findOne(id, userId);
    const previousStatus = existingTask.status;

    const updatedTask = await this.taskRepository.update(id, {
      ...updateTaskDto,
      dueDate: updateTaskDto.dueDate ? new Date(updateTaskDto.dueDate) : undefined,
      updatedAt: new Date(),
    });

    if (!updatedTask) {
      throw new NotFoundException(`Task with ID ${id} not found`);
    }

    const taskPayload = {
      task: this.entityToTask(updatedTask),
      workspaceId: updatedTask.workspaceId,
    };

    if (updateTaskDto.status && updateTaskDto.status !== previousStatus) {
      this.taskEventService.emitEvent(userId, TaskEventType.STATUS_CHANGED, taskPayload);
    } else {
      this.taskEventService.emitEvent(userId, TaskEventType.UPDATED, taskPayload);
    }

    return updatedTask;
  }

  async remove(id: string, userId: string): Promise<void> {
    const task = await this.findOne(id, userId);
    await this.taskRepository.delete(task.id);

    this.taskEventService.emitEvent(userId, TaskEventType.DELETED, {
      task: this.entityToTask(task),
      workspaceId: task.workspaceId,
    });
  }

  async deleteByWorkspaceId(workspaceId: string): Promise<void> {
    await this.taskRepository.deleteByWorkspaceId(workspaceId);
  }

  private entityToTask(entity: TaskEntity): Task {
    return {
      id: entity.id,
      userId: entity.userId,
      title: entity.title,
      description: entity.description,
      status: entity.status,
      priority: entity.priority,
      dueDate: entity.dueDate,
      tags: entity.tags,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    };
  }
}
