import { Injectable, NotFoundException, ForbiddenException, Inject } from '@nestjs/common';
import { ITaskRepository } from '../../domain/interfaces/task.repository.interface';
import { TaskEntity } from '../../domain/entities/task.entity';
import { CreateTaskDto, UpdateTaskDto } from '../dto';
import { TaskStatus, TaskPriority } from '@task-manager/types';

@Injectable()
export class TaskService {
  constructor(@Inject('ITaskRepository') private readonly taskRepository: ITaskRepository) {}

  async create(userId: string, createTaskDto: CreateTaskDto): Promise<TaskEntity> {
    const task = new TaskEntity(
      '', // Will be generated by repository
      userId,
      createTaskDto.title,
      createTaskDto.description,
      createTaskDto.status || TaskStatus.TODO,
      createTaskDto.priority || TaskPriority.MEDIUM,
      createTaskDto.dueDate ? new Date(createTaskDto.dueDate) : undefined,
      createTaskDto.tags || [],
    );

    return this.taskRepository.create(task);
  }

  async findAll(userId: string, params?: any): Promise<TaskEntity[]> {
    return this.taskRepository.findByUserId(userId, params);
  }

  async findOne(id: string, userId: string): Promise<TaskEntity> {
    const task = await this.taskRepository.findById(id);

    if (!task) {
      throw new NotFoundException(`Task with ID ${id} not found`);
    }

    if (task.userId !== userId) {
      throw new ForbiddenException('You do not have access to this task');
    }

    return task;
  }

  async update(id: string, userId: string, updateTaskDto: UpdateTaskDto): Promise<TaskEntity> {
    await this.findOne(id, userId);

    const updatedTask = await this.taskRepository.update(id, {
      ...updateTaskDto,
      dueDate: updateTaskDto.dueDate ? new Date(updateTaskDto.dueDate) : undefined,
      updatedAt: new Date(),
    });

    if (!updatedTask) {
      throw new NotFoundException(`Task with ID ${id} not found`);
    }

    return updatedTask;
  }

  async remove(id: string, userId: string): Promise<void> {
    const task = await this.findOne(id, userId);
    await this.taskRepository.delete(task.id);
  }
}
